### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-typescript#167]
From @Strum355 in Slack:

> Just as a notice, scip-typescript is causing OOMs when indexing client/ subdirectories of sourcegraph/sourcegraph on 16gb executor machines, with 2 running in parallel per machine. The machines on s2 are technically the wrong size (should have more memory), but I think itd be good to have scip-typescript use considerably less ram

**Comment by olafurpg** [comment]
Closing this until we have a reliable reproduction.
