### ISSUE TITLE
Is the location of the code blocks of the symbol implementation emitted anywhere?

### ISSUE THREAD

**Issue by jmy48** [sourcegraph/scip-typescript#278]
E.g., for function or class definition symbols, I would like to know the location of the associated body, which would in most circumstances be multi-line. However, the index generated has only 3 number ranges, which probably means only the location of the symbol token is emitted.

If not, will it be supported in the future? I essentially want to support a feature similar to seeing the implementation code block when hovering over symbols in VS Code.

**Comment by jdorfman** [comment]
Thanks for reaching out @jmy48. @SuperAuguste whatcha think?

**Comment by SuperAuguste** [comment]
@jmy48 check out https://github.com/sourcegraph/scip/blob/main/scip.proto#L619 :) - we don't support this in scip-typescript yet, but we're always open to PRs!

**Comment by jmy48** [comment]
That's unfortunate, could you estimate the complexity of the task if I were to try to do it? (# of days with no prior knowledge)

**Comment by kritzcreek** [comment]
Can we close this after https://github.com/sourcegraph/scip-typescript/pull/308 was merged?

**Comment by varungandhi-src** [comment]
Yes, it is OK to close this now - we support this via `enclosing_range`
