### ISSUE TITLE
Add Dockerfiles for releases and development

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-typescript#3]
We need two main Dockerfiles:

1. Similar to lsif-node, one that provides the latest release of `lsif-typescript`.
2. Unlike lsif-node, one for local development so which can be used for testing changes to auto-indexing locally.
    - Maybe add an NPM build command for rebuilding the docker image.
    - Suggesting changing the image variable in `infer/typescript.go` to point to the locally built image.

**Comment by olafurpg** [comment]
Closing as fixed. The CI published two images

- sourcegraph/lsif-java:VERSION the latest release
- sourcegraph/lsif-java:autoindex the latest release with `src` pre-installed and a custom `lsif-typescript-autoindex` script that handles LSIF Typed conversion. I think we could honestly drop this image in the future by embedding both of those into the default image. It's possible to build this image locally and test it with auto-indexing.
