### ISSUE TITLE
How to locate definitions of variable type?

### ISSUE THREAD

**Issue by zhengchenghang** [sourcegraph/scip-typescript#359]
After indexing the TS project, I use a Java library for parsing, and I can obtain the local variable names and their corresponding type names. However, I want to further locate the type definition positions to retrieve the type definition information. How should I proceed? Because the documentation for local variable symbols only provides the type names, it does not specify the file path where the type definition is located.

**Comment by varungandhi-src** [comment]
If you have a SCIP symbol (https://github.com/sourcegraph/scip/blob/main/scip.proto#L147-L179) for the type name, you can search all the [`symbols`](https://github.com/sourcegraph/scip/blob/main/scip.proto#L96) in all [`documents`](https://github.com/sourcegraph/scip/blob/main/scip.proto#L27) in the index to see which has the [`symbol`](https://github.com/sourcegraph/scip/blob/main/scip.proto#L234) field that matches the symbol. Then you can search for a [definition](https://github.com/sourcegraph/scip/blob/main/scip.proto#L506) [occurrence](https://github.com/sourcegraph/scip/blob/main/scip.proto#L90) in that Document.

**Comment by varungandhi-src** [comment]
Closing this as implementing code nav itself is not exactly part of scip-typescript's set of functionality.
