### ISSUE TITLE
Update pretty-printing of signatures in hover messages to mimic the formatting in hovers from the TypeScript language server

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/scip-typescript#53]
tsserver includes the name of the symbol and a keyword to denote the syntax kind (const/class/interface/...)

![CleanShot 2022-03-23 at 15 44 21](https://user-images.githubusercontent.com/1408093/159726178-dc8b10ff-249b-48bd-a54d-42e499bd98d5.png)
![CleanShot 2022-03-23 at 15 38 48](https://user-images.githubusercontent.com/1408093/159726182-228878d8-16ad-45ed-bbce-1aa14e4e356b.png)

**Comment by varungandhi-src** [comment]
Do we want this to be 1:1 with the old implementation or should we approximate it? The old implementation used to get this to work by starting with a `LanguageService` → [use `getQuickInfoAtPosition`](https://github.com/sourcegraph/lsif-node/blob/7bd28f35b0de657e33c04838ae928917aacfea36/src/lsif.ts#L2853) → the QuickInfo carries a `displayParts` field, call `ts.displayPartsToString` on that.

However, we don't have access to a `LanguageService` object right now and the lower level API which handles the various cases [`ts.SymbolDisplay.getSymbolDisplayPartsDocumentationAndSymbolKind`](https://sourcegraph.com/github.com/microsoft/TypeScript/-/blob/src/services/symbolDisplay.ts?L138:21) is not public. Also, that function itself is over 500 lines long, so copy-pasting it in-tree seems like a bit too much. 😬

So the main options seem to be:
- Create a `LanguageService` object and use the old way of getting the hover text.
- Code a bunch of simple if checks on the node syntax kind and emit text based on that.

**Comment by olafurpg** [comment]
> Do we want this to be 1:1 with the old implementation or should we approximate it?

I think it's best to approximate. The biggest change we need to make is

* Add the symbol kind in parentheses, example `(property)`
* Add the symbol name
* Add whatever tokens to make it look like valid syntax, like a `const` keyword or a `:` colon in `const x: Type`
