### ISSUE TITLE
Add test cases for JavaScript

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-typescript#76]
Right now, we don't really have any test cases for JavaScript. We should add some, and maybe try indexing some larger JavaScript projects.

**Comment by olafurpg** [comment]
We have a minimal JS-only snapshot test in https://github.com/sourcegraph/scip-typescript/tree/main/snapshots/input/pure-js 

We can add more cases to this project as we encounter more bugs. Closing this as fixed.
